# Generated by Django 5.0.4 on 2024-05-01 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_customer_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='assigned_helper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to='app1.helper'),
        ),
    ]
