# Generated by Django 5.0.4 on 2024-05-01 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_customer_assigned_helper'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='assigned_customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helper_assignment', to='app1.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='assigned_helper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_assignment', to='app1.helper'),
        ),
    ]
